steps:
#Building the docker image
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', '$LOCATION-docker.pkg.dev/$PROJECT_ID/cicd-demo/demo-image:$SHORT_SHA', '.' ]
  id: build


#Running the tests
- name: $LOCATION-docker.pkg.dev/$PROJECT_ID/hello-world-python/hello-world-python
  entrypoint: python
  args: ["-m","pytest","unit_tests.py"]
  id: test

#Pushing the image to AR
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "$LOCATION-docker.pkg.dev/$PROJECT_ID/cicd-demo/demo-image:$SHORT_SHA"]
  id: push


#Starting the cloud deploy release to deploy the manifest
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
  - '-c'
  - > 
    gcloud deploy releases create release-$SHORT_SHA
    --delivery-pipeline=gke-pipe
    --region=$LOCATION
    --images=IMAGE_NAME="$LOCATION-docker.pkg.dev/$PROJECT_ID/cicd-demo/demo-image:${SHORT_SHA}"
  id: deploy
images:
  - $LOCATION-docker.pkg.dev/$PROJECT_ID/cicd-demo/demo-image:$SHORT_SHA
options:
  logging: CLOUD_LOGGING_ONLY