apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-demo-des
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cicd-demo-des
  template:
    metadata:
      labels:
        app: cicd-demo-des
    spec:
      containers:
      - name: cicd-demo-des
        image: IMAGE_NAME
---
apiVersion: v1
kind: Service
metadata:
  name: cicd-demo-service-des
spec:
  selector:
    app: cicd-demo-des
  ports:
  - protocol: TCP
    port: 80
