apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-demo-des
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cicd-demo-des
  template:
    metadata:
      labels:
        app: cicd-demo-des
    spec:
      containers:
      - name: cicd-demo-des
        image: IMAGE_NAME
        ports:
        - containerPort: 8080
        env:
          - name: PORT
            value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: cicd-demo-service-des
spec:
  type: LoadBalancer
  selector:
    app: cicd-demo-des
  ports:
  - port: 80
    targetPort: 8080
