apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: my-automation-demo-app-1
description: Automation demonstration pipeline
serialPipeline:
  stages:
  - targetId: run-dev
    profiles: [dev]
  - targetId: run-uat
    profiles: [uat]
  - targetId: run-prd
    profiles: [prd]
    strategy:
      canary:
        runtimeConfig:
          cloudRun:
            automaticTrafficControl: true
        canaryDeployment:
          percentages: [50]
          verify: false
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: automation-quickstart-dev
description: Dev cluster to demonstrate deploy automation
run:
  location: projects/smb-challenge/locations/us-central1
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: automation-quickstart-staging
description: Staging cluster to demonstrate deploy automation
run:
  location: projects/smb-challenge/locations/us-central1
---

apiVersion: deploy.cloud.google.com/v1
kind: Automation
metadata:
  name: my-automation-demo-app-1/promote
description: Promotes a release to the next target
suspended: false
serviceAccount: 946356562346-compute@developer.gserviceaccount.com
selector:
  targets:
  - id: automation-quickstart-dev
rules:
- promoteReleaseRule:
    name: "promote-release"
    wait: 1m
    toTargetId: "@next"
---

apiVersion: deploy.cloud.google.com/v1
kind: Automation
metadata:
  name: my-automation-demo-app-1/advance
description: advances a rollout
suspended: false
serviceAccount: 946356562346-compute@developer.gserviceaccount.com
selector:
  targets:
  - id: automation-quickstart-staging
rules:
- advanceRolloutRule:
    name: "advance-rollout"
    sourcePhases: ["canary-50"]
    wait: 1m